eureka:
  client:
    serviceUrl:
      defaultZone: https://eureka-8c08f6a0-dcc7-4872-9e9c-f32238d7b1a4.apps.cumuluslabs.io
    instance-info-replication-interval-seconds: 5
    initial-instance-info-replication-interval-seconds: 6

