eureka:
  client:
    serviceUrl:
      defaultZone: https://eureka-2326c419-b7f3-4258-9624-7b8fe92def7f.apps.cumuluslabs.io
    instance-info-replication-interval-seconds: 5
    initial-instance-info-replication-interval-seconds: 6

